spring.application.name=hotel
# Server
server.port=8080

# MySQL Database (Step ⑥)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret (Keep this secure in production env variables)
app.jwt.secret=YourSuperSecretKeyForHotelManagementSystem123!
app.jwt.expiration-ms=86400000